Add a comment in the examples/ folder for each example program explaining how to run it #115
spdx/tools-golang pull request #123
Opened 2022-03-28 07:45 UTC by CatalinStratu

Hi @swinslow , I have added the necessary changes mentioned in #120

2022-03-28 15:02 UTC, seabass-labrax requested changes
Looks great, @CatalinStratu! I've left a few comments that probably ought to be fixed before this is merged. If you come up against issues when force-pushing to your fork (in order to update the pull request), please let me know and I'll be happy to help :)

2022-03-28 15:15 UTC, swinslow commented
Hi @CatalinStratu, thanks for this! I haven't had a chance to review in detail yet (or to look at @seabass-labrax's feedback either), but one quick note:

Please take another look at my comment at https://github.com/spdx/tools-golang/pull/120#issuecomment-1079952170. I mentioned that the files to go into an `examples/sample-docs/` folder should just be the SPDX documents themselves, and not e.g. README files or code. It looks like this PR is still reinserting some of the README files from the spdx-examples repo.

Can you please take another look, and revise so that this is just adding the SPDX documents and nothing else for the `sample-docs/` folder?

2022-03-28 16:21 UTC, CatalinStratu commented
> Hi @CatalinStratu, thanks for this! I haven't had a chance to review in detail yet (or to look at @seabass-labrax's feedback either), but one quick note:
> 
> Please take another look at my comment at [#120 (comment)](https://github.com/spdx/tools-golang/pull/120#issuecomment-1079952170). I mentioned that the files to go into an `examples/sample-docs/` folder should just be the SPDX documents themselves, and not e.g. README files or code. It looks like this PR is still reinserting some of the README files from the spdx-examples repo.
> 
> Can you please take another look, and revise so that this is just adding the SPDX documents and nothing else for the `sample-docs/` folder?

I made the necessary changes. Please review it.

2022-03-28 16:22 UTC, CatalinStratu commented on examples/README.md
> +*
The README.md file no longer exists.

2022-03-29 12:20 UTC, seabass-labrax approved these changes
Excellent! Nice work, @CatalinStratu :smile:

2022-03-30 08:16 UTC, CatalinStratu commented
> Excellent! Nice work, @CatalinStratu 😄

Thanks, @swinslow , what do you think?

2022-03-31 00:25 UTC, swinslow commented on examples/6-licensediff/example_licensediff.go
> +// Run project: go run example_licensediff.go ../sample-docs/example1/spdx/example1.spdx ../sample-docs/example2/spdx/example2-src.spdx
This does appear to be a bug in either the tvloader parser or else possible the example file. I see that @CatalinStratu filed #124 so we can take a look there.

@CatalinStratu please note though that the files in example1/spdx/... and example2/spdx/... are not actually the same. They have the same filename, but take a look and you'll see that the contents are different. We can dig into this further in #124.

2022-03-31 00:27 UTC, swinslow commented on examples/README.md
> +*
@seabass-labrax is correct, this is in the main examples/README.md file so this does need a fix. I'll update separately after merging this PR.

2022-03-31 00:29 UTC, swinslow commented
Thank you @CatalinStratu! There are a couple of subsequent tweaks but I can address them in a subsequent PR.

I'm going to squash these commits since it looks like the submitted ones have the extra README files getting added and then deleted.

2022-03-31 00:30 UTC, merged