Error string should not be capitalized or end with the punctuation mark
spdx/tools-golang pull request #178
Opened 2022-12-30 22:27 UTC by CatalinStratu

Error strings should not be capitalized (unless beginning with proper nouns or acronyms) or end with punctuation, since they are usually printed following other context. That is, use fmt.Errorf("something bad") not fmt.Errorf("Something bad"), so that log.Printf("Reading %s: %v", filename, err) formats without a spurious capital letter mid-message. This does not apply to logging, which is implicitly line-oriented and not combined inside other messages.

Source: https://github.com/golang/go/wiki/CodeReviewComments#error-strings

2022-12-30 23:44 UTC, CatalinStratu commented
Hi, @lumjjb please review.

2023-01-02 11:26 UTC, CatalinStratu commented
@swinslow and @RishabhBhatnagar, what do you think about this PR?

2023-01-02 11:32 UTC, RishabhBhatnagar requested changes

2023-01-02 15:23 UTC, CatalinStratu commented on rdfloader/parser2v2/license_utils_test.go
> -		<spdx:Checksum>
@RishabhBhatnagar can you look again?

2023-01-03 03:53 UTC, RishabhBhatnagar requested changes

2023-01-03 03:53 UTC, RishabhBhatnagar commented on rdfloader/parser2v2/license_utils.go
> +// ToLicenseString TODO: should probably add brackets while linearizing a nested license.
avoid adding Function names before the function unless the following statement captures the intent of the function.

2023-01-03 03:53 UTC, RishabhBhatnagar commented on rdfloader/parser2v2/license_utils.go
> +// ToLicenseString TODO: should probably add brackets while linearizing a nested license.
Same comment here and in the other files as well.

2023-01-03 03:55 UTC, RishabhBhatnagar commented
This is kind of a cosmetic change. I haven't kept track of other PRs. 
I'm afraid that it might cause merge conflicts for them.

2023-01-04 08:27 UTC, lumjjb commented
Hi @CatalinStratu ! Yes you are right, this will likely merge conflict with the PR that @kzantow is working on: https://github.com/spdx/tools-golang/pull/172, which involves a major refactor, can we put this on hold until that PR gets in and apply the changes once that gets merged? Which should be before the end of the month 🤞

2023-01-17 21:44 UTC, kzantow commented
Hi @CatalinStratu -- apologies for the large number of conflicts! There has been a significant refactoring to make this library easier for consumers; are you able to adjust this PR for the changes?

2023-01-17 21:52 UTC, CatalinStratu commented
Hi, @kzantow will adapt this PR for the new changes.

2023-05-18 13:37 UTC, lumjjb commented
Closing from inactivity, opened #216 to track since this seems valuable.

2023-05-18 13:37 UTC, closed without merging